<?xml version="1.0"?>
<package format="3">
  <name>wildebeest_bringup</name>
  <version>0.1.0</version>
  <description>Hardware, localization, command multiplexing, and teleoperation bringup.</description>
  <maintainer email="maintainers@wildebeest-pro.org">Wildebeest Pro maintainers</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nmea_navsat_driver</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rplidar_ros</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>twist_mux</exec_depend>
  <exec_depend>v4l2_camera</exec_depend>
  <exec_depend>wildebeest_base</exec_depend>
  <exec_depend>wildebeest_description</exec_depend>
  <exec_depend>xacro</exec_depend>

  <test_depend>ament_cmake_xmllint</test_depend>
  <test_depend>ament_lint_auto</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
