twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: /cmd_vel/navigation
        timeout: 0.5
        priority: 10
      remote:
        topic: /cmd_vel/remote
        timeout: 0.35
        priority: 40
      teleop:
        topic: /cmd_vel/teleop
        timeout: 0.35
        priority: 50
    locks:
      emergency_stop:
        topic: /wildebeest/estop
        timeout: 0.0
        priority: 255
