<?xml version="1.0"?>
<package format="2">
  <name>wildebeest_bringup</name>
  <version>0.1.0</version>
  <description>Composable hardware, sensor, teleoperation, diagnostics, localization, and navigation launches.</description>

  <maintainer email="maintainers@wildebeest-pro.org">Wildebeest Pro Maintainers</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>diagnostic_aggregator</exec_depend>
  <exec_depend>gscam</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>nmea_navsat_driver</exec_depend>
  <exec_depend>rplidar_ros</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>teleop_twist_keyboard</exec_depend>
  <exec_depend>twist_mux</exec_depend>
  <exec_depend>wildebeest_base</exec_depend>
  <exec_depend>wildebeest_description</exec_depend>
  <exec_depend>wildebeest_navigation</exec_depend>

  <export/>
</package>
